# docker-compose up -d
version: '3'
services:
  db:
    image: mysql
    container_name: csa_mysql
    volumes:
      # 路径需要根据服务器具体情况修改
      - ./data/db:/var/lib/mysql
      # 将容器中运行的mysql数据保存到宿主机，防止容器删除后数据丢失
      - ./service/mysql/mysql.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      #数据库初始话为root用户设置的默认密码
      MYSQL_DATABASE: code_shared
      #数据库名
      MYSQL_USER: code_shared
      #自定义数据库的用户，权限只作用于MYSQL_DATABASE配置的数据库
      MYSQL_PASSWORD: code_shared
      #自定义数据库的用户，权限只作用于MYSQL_DATABASE配置的数据库
  web:
    image: nginx
    container_name: csa_nginx
    restart: always
    ports:
      - 8055:80
      - 8060:8090
    volumes:
      - ./service/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  koa:
    image: code-shared-awesome-koa:0.0.1
    container_name: csa_koa
    ports:
      - 8000:3000
    volumes:
      - ./log:/usr/csa_koa/log
